  name: Test2

  on:
    workflow_run:
      workflows: [Test1]
      types:
        - completed

  jobs:
    run_test:
      runs-on: ubuntu-latest
      steps:
        - name: Tests start
          env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
          run: |
            echo "$GITHUB_CONTEXT"
