
  name: Test1

  on:
    workflow_dispatch:
      inputs:
        stage:
          description: Stage number
          required: true
          type: choice
          options:
            - '1'
            - '2'
            - '3'
        run_tests:
          description: Run tests
          type: boolean
          required: false
          default: false

  jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout repository
        run: exit 0
  