name: Test3

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - run_tests

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Test 3
      run: |
        echo "${{ github.event.client_payload.stage_server }}"
