name: Test3

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - run_tests

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Update check status
      run: |
        curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
          "context": "tests",
          "state": "pending",
          "description": "Staging tests passed",
          "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        }'
    - name: Get branch pull requests
      env:
        HEAD_REF_NAME: ${{ github.ref_name}}
        CURRENT_REPOSITORY: ${{ github.event.repository.name }}
        CURRENT_REPOSITORY_OWNER: ${{ github.repository_owner }}
      run: |
        curl -X POST https://api.github.com/graphql \
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        -H "Content-Type: application/json" \
        -d '{"query":"{repository(owner:\"${{ github.repository_owner }}\",name:\"${{ github.event.repository.name }}\"){pullRequests(first: 1,headRefName:\"${{ github.ref_name}}\",states:[OPEN],orderBy:{field:CREATED_AT, direction:DESC}){nodes{number}}}}"}' > \
        pulls.json
    - name: Parse pull requests
      id: pr-number-parse
      uses: actions/github-script@v6
      with:
        script: |
          const pulls = require('./pulls.json')
          const lastPull = pulls.data.repository.pullRequests.nodes.shift()
          if (lastPull) {
            core.setOutput('pr_number', String(lastPull.number))
          }
    - name: Update status
      if: steps.pr-number-parse.outputs.pr_number
      uses: thollander/actions-comment-pull-request@v2
      with:
        comment_tag: e2e_tests
        pr_number: ${{ steps.pr-number-parse.outputs.pr_number }}
        message: |
          Tests running ...
    - name: Test 3
      run: |
        echo "${{ github.event.client_payload.env }}"
    - name: Update status
      if: steps.pr-number-parse.outputs.pr_number
      uses: thollander/actions-comment-pull-request@v2
      with:
        comment_tag: e2e_tests
        pr_number: ${{ steps.pr-number-parse.outputs.pr_number }}
        message: |
          Tests passed!
    - name: Update if success
      if: ${{ success() }}
      run: |
        curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
          "context": "tests",
          "state": "success",
          "description": "Staging tests passed",
          "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        }'
    - name: Update if failure
      if: ${{ failure() }}
      run: |
        curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
          "context": "tests",
          "state": "failure",
          "description": "Staging tests passed",
          "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        }'