
  name: Test1

  on:
    workflow_dispatch:
      inputs:
        stage:
          description: Stage number
          required: true
          type: choice
          options:
            - '1'
            - '2'
            - '3'
        run_tests:
          description: Run tests after deploy
          type: boolean
          required: false
          default: false

  jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Run Action A
        run: |
          # Run your logic for actionA
          # Collect the required parameters (e.g., BRANCH_NAME and STAGE_SERVER)
          # Set them as environment variables using `echo` command
          echo "STAGE=${{ github.event.inputs.stage }}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
  
      - name: Trigger Action B
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: actionB
          client-payload: '{"branch_name": "${{ env.BRANCH_NAME }}", "stage_server": "${{ env.STAGE }}" }'