name: Test 2

on: [push]

jobs:
  precheck:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - name: Update check status
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "e2e_tests",
            "state": "success",
            "description": "e2e skipped!",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'