name: Test3

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - run_tests

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Get branch pull requests
      env:
        HEAD_REF_NAME: ${{ github.ref_name}}
        CURRENT_REPOSITORY: ${{ github.event.repository.name }}
        CURRENT_REPOSITORY_OWNER: ${{ github.repository_owner }}
      run: |
        curl -i -X POST https://api.github.com/graphql \
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        -H "Content-Type: application/json" \
        --data-raw '{
          "query":
            "{
              repository(owner:\""$CURRENT_REPOSITORY_OWNER"\", name:\""$CURRENT_REPOSITORY"\") {
                pullRequests (first: 1, headRefName:\""$HEAD_REF_NAME"\", states:[OPEN]) {
                  nodes {
                    id
                  }
                }
              } 
            }"
          }
        }' > \
        pulls.json
    - name: output
      run: cat pulls.json
    - name: Update status
      if: github.event.client_payload.pr_number
      uses: thollander/actions-comment-pull-request@v2
      with:
        pr_number: ${{ github.event.client_payload.pr_number }}
        message: |
          Tests running ...
    - name: Test 3
      run: |
        echo "${{ github.event.client_payload.env }}"
    - name: Update status
      if: github.event.client_payload.pr_number
      uses: thollander/actions-comment-pull-request@v2
      with:
        comment_tag: e2e_tests
        pr_number: ${{ github.event.client_payload.pr_number }}
        message: |
          Tests passed!