
  name: Test1

  on:
    workflow_dispatch:
      inputs:
        stage:
          description: Stage number
          required: true
          type: choice
          options:
            - '1'
            - '2'
            - '3'
        run_tests:
          description: Run tests
          type: boolean
          required: false
          default: false

  jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:
      - name: Run Action A
        run: exit 0
    run_tests:
      if: github.event.inputs.run_tests == 'true'
      needs: [build]
      name: Start tests
      uses: peter-evans/repository-dispatch@v2
      with:
        event-type: stage_tests