  name: Test2

  on:
    workflow_run:
      workflows: [Test1]
      types:
        - completed

  jobs:
    run_test:
      permissions:
        actions: read
        contents: read
        security-events: write
      runs-on: ubuntu-latest
      steps:
        - name: 'Download flag'
          uses: actions/github-script@v6
          with:
            script: |
              let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
                 owner: context.repo.owner,
                 repo: context.repo.repo,
                 run_id: context.payload.workflow_run.id,
              });
              console.log(JSON.stringify(allArtifacts))
              let flagArtifact = allArtifacts.data.artifacts.find((artifact) => {
                return artifact.name == "run_tests_flag"
              });
              let download = await github.rest.actions.downloadArtifact({
                 owner: context.repo.owner,
                 repo: context.repo.repo,
                 artifact_id: flagArtifact.id,
                 archive_format: 'zip',
              });
              let fs = require('fs');
              fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/run_tests`, Buffer.from(download.data));
        - name: Tests start
          run: |
            value=`cat run_tests`
            echo $value
        - name: 'Comment on PR'
          uses: actions/github-script@v6
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
              let fs = require('fs');
              let issue_number = Number(fs.readFileSync('./pr_number'));
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue_number,
                body: 'Thank you for the PR!'
              });
