name: Test3

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - run_tests

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Debug
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
    - name: Update status
      if: github.event.client_payload.pr_number
      uses: thollander/actions-comment-pull-request@v2
      with:
        pr_number: ${{ github.event.client_payload.pr_number }}
        message: |
          Tests running ...
    - name: Test 3
      run: |
        echo "${{ github.event.client_payload.env }}"
    - name: Update status
      if: github.event.client_payload.pr_number
      uses: thollander/actions-comment-pull-request@v2
      with:
        pr_number: ${{ github.event.client_payload.pr_number }}
        message: |
          Tests passed!