name: Test 2

on: [push]

jobs:
  precheck:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check e2e_tests status
        run: |
          curl -L \
          --header 'accept: application/vnd.github+json' \
          --header 'content-type: application/json' \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'\
          --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/statuses \
          > statuses.json
      - name: Parse statuses
        id: commit-status-check
        uses: actions/github-script@v6
        with:
          script: |
            const data = require('./statuses.json')
            core.setOutput('test', JSON.stringify(data))
            if (false) {
              const tests = data.find(s => s.context === 'e2e_tests')
              if (tests.description.startsWith('Expected')) {
                core.setOutput('update_flag', 'true')
              }
            }
      - name: Debug
        env:
          DEBUG_TEST: ${{ steps.commit-status-check.outputs.test }}
        run: |
          echo $DEBUG_TEST
      - name: Update check status
        if: ${{ steps.commit-status-check.outputs.update_flag }}
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "e2e_tests",
            "state": "success",
            "description": "Skipped",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'