name: Test 2

on: [push]

jobs:
  precheck:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Debug
        env:
          DEBUG_TEST: ${{ toJson(github) }}
        run: |
          echo $DEBUG_TEST
      - name: Update check status
        if: ${{ github.run_attempt == '1' }}
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "e2e_tests",
            "state": "success",
            "description": "Skipped",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'